// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMT_dH7kI8S4jdeC4_JlpNMw2HhW6XYoI',
    appId: '1:1035090598395:web:7405b900664e697263d35e',
    messagingSenderId: '1035090598395',
    projectId: 'flutter-new-chat-app',
    authDomain: 'flutter-new-chat-app.firebaseapp.com',
    storageBucket: 'flutter-new-chat-app.appspot.com',
    measurementId: 'G-0W8MCF9CC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-UT_URQog7S4nIJm24U4oWkBMnZ8foLs',
    appId: '1:1035090598395:android:dbb8b0e7b18bd10863d35e',
    messagingSenderId: '1035090598395',
    projectId: 'flutter-new-chat-app',
    storageBucket: 'flutter-new-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV82kmOr75qAIciUOT-jmFhqIcr14IqlU',
    appId: '1:1035090598395:ios:1b4ee00424e1ed1863d35e',
    messagingSenderId: '1035090598395',
    projectId: 'flutter-new-chat-app',
    storageBucket: 'flutter-new-chat-app.appspot.com',
    iosClientId: '1035090598395-kng4lgs91pks16hqh2dj5gj0ltb4pttp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV82kmOr75qAIciUOT-jmFhqIcr14IqlU',
    appId: '1:1035090598395:ios:1b4ee00424e1ed1863d35e',
    messagingSenderId: '1035090598395',
    projectId: 'flutter-new-chat-app',
    storageBucket: 'flutter-new-chat-app.appspot.com',
    iosClientId: '1035090598395-kng4lgs91pks16hqh2dj5gj0ltb4pttp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
